build-FfmpegLayer:
	wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
	tar xvf ffmpeg-release-amd64-static.tar.xz
	mkdir -p "$(ARTIFACTS_DIR)/bin"
	cp ffmpeg-6.1-amd64-static/ffmpeg "$(ARTIFACTS_DIR)/bin/ffmpeg"